id: I4CC9A1C8
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T03:19:38.142893'
last_modified: '2022-06-19T03:19:38.143750'
parser: null
source_metadata:
  title: Kun dga blo gross (1729–1783) Sakya Genealogy Supplement
  author: བདག་ཆེན་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2011-03); converted
    from external file, revision in process, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mrs. Lhandzom Everding (Bonn), pp. 1-150 (le), Dawa Dhondup (Dehradun)
    (dd)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:Dawa (dd), editors (ed)
  text_witnesses: https://sakyaresearch.org/sources/229
  bases:
    e45f:
      title: Kun dga blo gross (1729–1783) Sakya Genealogy Supplement
      order: 1
      base_file: e45f.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
